### ISSUE TITLE
It doesn't compile

### ISSUE THREAD

**Issue by FloRide1** [IUT-Theophile-Wemaere/Matlab#1]
Yeah, i don't understand, could you please explain me. Ah wait a second it's because it's a matlab script a shit, ok well my bad, sry

**Comment by IUT-Theophile-Wemaere** [comment]
I tried to run it with python but now my code is being compiled by spotify

**Comment by IUT-Theophile-Wemaere** [comment]
tried to run it with python but now my code is being compiled by spotify

**Comment by FloRide1** [comment]
Okay tks, i've tried to hack it with kali linux and  make a html / css script compile with LaTeX but it didn't work.
Do you think if i use parrot os it will work ?

**Comment by IUT-Theophile-Wemaere** [comment]
I only use html to hack nasa, maybe you should try Windows, it's a great open source OS perfect for hacking matlab script
